name: Post welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env: 
          GITHUB TOKEN: ${{ github.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 }}
          PR_URL: ${{ github.event.pull_request.html_url }}

  
